### ISSUE TITLE
Is draft feature really needed?

### ISSUE THREAD

**Issue by hanamura** [hanamura/gulp-minisite#36]

**Comment by reevader** [comment]
Don't know about drafts:)
What about template folder configs?
Is it possible to put 'template' folder elsewhere, not only root folder with gulpfile.js?
Definitely not a requirement, just a flexible approach.
i.e., I'd like being able to drop 'template' folder into src folder

**Comment by hanamura** [comment]
@reevader 

It may not be related to this issue, but you can put `template` folder elsewhere you like.

```js
var nunjucks = require('gulp-minisite/src/engines/nunjucks');

...

minisite({
	templateEngine: nunjucks({path: 'src/template'})
})
```

(An irrelevant code excluded. You, of course, have to write `minisite()` inside a gulp task.)

Note: however `'gulp-minisite/src/engines/nunjucks'` is too verbose, so I may change its path in the future version.

**Comment by reevader** [comment]
Yep, sorry, didn't want to open a new issue for such a minor modification.
That's exactly what I did - changed the 'templateEngine' line. Works fine for my purpose.
Thank you :)

**Comment by hanamura** [comment]
Remove draft in v5.0 because I rarely use it and there are alternative methods.
